### ISSUE TITLE
no such instruction: `rdseed %esi'

### ISSUE THREAD

**Issue by semenov-vladyslav** [agievich/bee2#1]
При сборке в Linux с помощью gcc возникает ошибка ассемблера: no such instruction: `rdseed %esi'. 
Нужно добавить проверку возможности использования компилятором инструкции rdseed (и rdrand) на этапе конфигурации проекта (например, компилятор msvc-2013 понимает инструкции rdrand, rdseed, хотя в x64 невозможно использовать ассемблерные вставки; компилятор gcc-4.9.2 в Debian x86_64 понимает rdrand, но не понимает rdseed).

**Comment by agievich** [comment]
Проблемы с `rdseed` в gcc по-видимому остались в прошлом. Код для Visual Studio переписан. В целом выполнено переключение c `rdrand` на `rdseed` (см. https://github.com/agievich/bee2/commit/0a7128a05db394c73218301e6f658678ee830d3c).
