### ISSUE TITLE
Некорректное использование cpuid для проверки поддержки rdrand, rdseed.

### ISSUE THREAD

**Issue by semenov-vladyslav** [agievich/bee2#2]
Файл core/rng.c.
Для определения поддержки инструкции rdrand используется следующий код:
	/* rdrand? */
	__cpuid((int*)info, 1);
	 return (info[1] & 0x40000000) == 0x40000000;
Но проверять нужно значение (info[2] & 0x40000000) == 0x40000000;

В ветке #elif defined(__GNUC__) && (defined(__i386__) || defined(__x86_64__)) в функции rngReadTRNG используется инструкция rdseed (asm volatile ("rdseed %0; setc %1" : "=r" (*rand), "=qm" (ok));), но соответствующая проверка rngHasTRNG() проверяет (некорректно) поддержку инструкции rdrand.
Для поддержки инструкции rdseed нужно:
    __cpuid((int*)info, 7);
    return (info[1] & 0x40000) == 0x40000;

**Comment by agievich** [comment]
исправил
