### ISSUE TITLE
Invalid lock operation within rngCreate

### ISSUE THREAD

**Issue by semenov-vladyslav** [agievich/bee2#3]
"Compare and increment" atomic operation, implemented in rngCreate as

```
if (_lock)
{
  ++_lock;
  return ERR_OK;
}
```

is not atomic as two threads could simultaneously check condition and jump over. This may lead to issues with creating and using mutex `_mtx`. Suggested fix is to create mutex once in a global library initialization routine (e.g. bee2Init) and increment `_lock` within critical section.

**Comment by agievich** [comment]
The mutex `_mtx` is initialized in a concurrent-safe manner using the `mtCallOnce()` function. The mutex is destroyed when a program / shared_library is terminated / unloaded using a custom destructor registered with the `utilOnExit` function.
