### ISSUE TITLE
Недостижимый код в zzExGCD(), zzDivMod()

### ISSUE THREAD

**Issue by komisarenkov** [agievich/bee2#32]
В функциях `zzDivMod`  и `zzExGCD` в файле `zz_gcd.c`, присутствуют не достижимые участки кода, отвечающие за изменение переменных `sign` и `sign0`.
Например 
https://github.com/agievich/bee2/blob/cf0f75d033bdf603e95e5e4d8bed6810c27acafd/src/math/zz/zz_gcd.c#L420-L424

**Comment by agievich** [comment]
Функции `zzExGCD()`, `zzModDiv()` переписаны, избыточный код исключен.

Реализовано в https://github.com/agievich/bee2/commit/3c12571a07c86984643bdda49f2d3a1654c3534b.
