### ISSUE TITLE
Null pointer dereference / possible sensitive data leakage

### ISSUE THREAD

**Issue by luc-lynx** [agievich/bee2#5]
https://github.com/agievich/bee2/blob/7ad61a412ddf001298a2672835fd29d6206f5f2a/src/core/blob.c#L77

If NULL ptr is passed to the `blobWipe` function, it will be dereferenced and the app will crash. If `blob` is valid, it won't be wiped out and sensitive data will remain in memory.

Looks like a typo, it should be `if(blob != 0)`

**Comment by agievich** [comment]
blobWipe() was repaired. Thanks.
